# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'onder_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("QLabel{\n"
"color: #72777a;\n"
"font: 12pt \"Wix Madefor Display\";\n"
"}\n"
"QComboBox, QSpinBox{\n"
"background-color: transparent;\n"
"color: #72777a;\n"
"border: 0px;\n"
"selection-background-color: #2b2d2e;\n"
"font: 12pt \"Wix Madefor Display\";\n"
"}\n"
"QPushButton{\n"
"color: white;\n"
"font: 12pt \"Wix Madefor Display\";\n"
"border: 0px;\n"
"}\n"
"QWidget#centralwidget{\n"
"background-color: #1e1e1e;\n"
"}\n"
"QFrame#home_frame, #settings_frame, #mapping_frame{\n"
"border-radius: 20px;\n"
"}\n"
"QFrame#planner_frame{\n"
"border-radius: 10px;\n"
"background-color: #2b2d2e;\n"
"}\n"
"QPushButton#save_btn, #start_planner, #save_map{\n"
"border: 1px;\n"
"border-radius: 10px;\n"
"background-color: #0075ff;\n"
"}\n"
"QPushButton#save_btn:hover, #start_planner:hover, #save_map:hover{\n"
"background-color: #005dcc;\n"
"}\n"
"QPushButton#go_home,#reset_btn, #set_initial{\n"
"background-color: #2b2d2e;\n"
"boder: 1px;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#go_home:hover,#reset_btn:hover, #set_initial:hover{\n"
"background-color: #4e5254;\n"
"}\n"
"QPushButton#new_map{\n"
"color: #1fdf64;\n"
"}\n"
"QPushButton#new_map:hover{\n"
"color: #27ff76;\n"
"}\n"
"QPushButton#load_map, #set_timer{\n"
"color: #72777a;\n"
"}\n"
"QPushButton#load_map:hover, #set_timer:hover{\n"
"color:#959ca0;\n"
"}\n"
"QPushButton#station_1, #station_2, #station_3, #station_4, #station_01, #station_02, #station_03, #station_04{\n"
"color: #4e5254\n"
"}\n"
"QPushButton#station_1:hover, #station_2:hover, #station_3:hover, #station_4:hover, #station_01:hover, #station_02:hover, #station_03:hover, #station_04:hover{\n"
"color: #71777a;\n"
"}\n"
"QPushButton#close_settings, #close_mapping{\n"
"color: #4e5254;\n"
"font: 20pt \"Wix Madefor Display\";\n"
"}\n"
"QPushButton#close_settings:hover, #close_mapping:hover{\n"
"color: #71777a;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.top_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_btn = QtWidgets.QPushButton(self.frame)
        self.logo_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_btn.setStyleSheet("image: url(:/images/resources/onder.png);\n"
"border: 0px;")
        self.logo_btn.setText("")
        self.logo_btn.setObjectName("logo_btn")
        self.horizontalLayout_2.addWidget(self.logo_btn)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("QLabel{\n"
"color: white;\n"
"font: 20pt \"Wix Madefor Display\";\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.top_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.settings_btn = QtWidgets.QPushButton(self.frame_2)
        self.settings_btn.setMinimumSize(QtCore.QSize(0, 36))
        self.settings_btn.setStyleSheet("image: url(:/images/resources/settings.png);")
        self.settings_btn.setText("")
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout_3.addWidget(self.settings_btn)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.top_frame)
        self.central_frame = QtWidgets.QFrame(self.centralwidget)
        self.central_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_frame.setObjectName("central_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.central_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.home_frame = QtWidgets.QFrame(self.home_page)
        self.home_frame.setMinimumSize(QtCore.QSize(400, 500))
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.home_frame)
        self.verticalLayout_12.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_9 = QtWidgets.QFrame(self.home_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.home_png = QtWidgets.QLabel(self.frame_9)
        self.home_png.setMinimumSize(QtCore.QSize(0, 200))
        self.home_png.setStyleSheet("image: url(:/images/resources/lift.png);")
        self.home_png.setText("")
        self.home_png.setObjectName("home_png")
        self.verticalLayout_10.addWidget(self.home_png)
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spin_time = QtWidgets.QSpinBox(self.frame_9)
        self.spin_time.setMinimumSize(QtCore.QSize(0, 26))
        self.spin_time.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_time.setMaximum(999)
        self.spin_time.setObjectName("spin_time")
        self.horizontalLayout_7.addWidget(self.spin_time)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.set_timer = QtWidgets.QPushButton(self.frame_9)
        self.set_timer.setObjectName("set_timer")
        self.horizontalLayout_7.addWidget(self.set_timer)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.planner_frame = QtWidgets.QFrame(self.frame_9)
        self.planner_frame.setMaximumSize(QtCore.QSize(16777215, 36))
        self.planner_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.planner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.planner_frame.setObjectName("planner_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.planner_frame)
        self.horizontalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.planner_label = QtWidgets.QLabel(self.planner_frame)
        self.planner_label.setStyleSheet("color:white;")
        self.planner_label.setText("")
        self.planner_label.setObjectName("planner_label")
        self.horizontalLayout_9.addWidget(self.planner_label)
        self.backspace_btn = QtWidgets.QPushButton(self.planner_frame)
        self.backspace_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.backspace_btn.setStyleSheet("image: url(:/images/resources/backspace.png);")
        self.backspace_btn.setText("")
        self.backspace_btn.setObjectName("backspace_btn")
        self.horizontalLayout_9.addWidget(self.backspace_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.planner_frame)
        self.home_gridlayout = QtWidgets.QGridLayout()
        self.home_gridlayout.setObjectName("home_gridlayout")
        self.station_1 = QtWidgets.QPushButton(self.frame_9)
        self.station_1.setObjectName("station_1")
        self.home_gridlayout.addWidget(self.station_1, 0, 0, 1, 1)
        self.station_2 = QtWidgets.QPushButton(self.frame_9)
        self.station_2.setObjectName("station_2")
        self.home_gridlayout.addWidget(self.station_2, 0, 1, 1, 1)
        self.station_3 = QtWidgets.QPushButton(self.frame_9)
        self.station_3.setObjectName("station_3")
        self.home_gridlayout.addWidget(self.station_3, 1, 0, 1, 1)
        self.station_4 = QtWidgets.QPushButton(self.frame_9)
        self.station_4.setObjectName("station_4")
        self.home_gridlayout.addWidget(self.station_4, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.home_gridlayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.go_home = QtWidgets.QPushButton(self.frame_9)
        self.go_home.setMinimumSize(QtCore.QSize(0, 36))
        self.go_home.setObjectName("go_home")
        self.horizontalLayout_8.addWidget(self.go_home)
        self.start_planner = QtWidgets.QPushButton(self.frame_9)
        self.start_planner.setMinimumSize(QtCore.QSize(0, 36))
        self.start_planner.setObjectName("start_planner")
        self.horizontalLayout_8.addWidget(self.start_planner)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addWidget(self.frame_9)
        self.verticalLayout_11.addWidget(self.home_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.home_page)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.setting_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settings_frame = QtWidgets.QFrame(self.setting_page)
        self.settings_frame.setMinimumSize(QtCore.QSize(400, 500))
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.settings_frame)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.settings_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.close_settings = QtWidgets.QPushButton(self.frame_3)
        self.close_settings.setObjectName("close_settings")
        self.verticalLayout_3.addWidget(self.close_settings, 0, QtCore.Qt.AlignRight)
        self.settings_png = QtWidgets.QLabel(self.frame_3)
        self.settings_png.setMinimumSize(QtCore.QSize(0, 200))
        self.settings_png.setStyleSheet("image: url(:/images/resources/setting.png);")
        self.settings_png.setText("")
        self.settings_png.setObjectName("settings_png")
        self.verticalLayout_3.addWidget(self.settings_png)
        self.settings_info = QtWidgets.QLabel(self.frame_3)
        self.settings_info.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_info.setObjectName("settings_info")
        self.verticalLayout_3.addWidget(self.settings_info)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.maps_line = QtWidgets.QComboBox(self.frame_3)
        self.maps_line.setMinimumSize(QtCore.QSize(0, 26))
        self.maps_line.setStyleSheet("background-color: transparent;\n"
"color: #72777a;")
        self.maps_line.setObjectName("maps_line")
        self.horizontalLayout_5.addWidget(self.maps_line)
        self.load_map = QtWidgets.QPushButton(self.frame_3)
        self.load_map.setMinimumSize(QtCore.QSize(0, 36))
        self.load_map.setStyleSheet("")
        self.load_map.setObjectName("load_map")
        self.horizontalLayout_5.addWidget(self.load_map)
        self.new_map = QtWidgets.QPushButton(self.frame_3)
        self.new_map.setMinimumSize(QtCore.QSize(0, 36))
        self.new_map.setObjectName("new_map")
        self.horizontalLayout_5.addWidget(self.new_map)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.settings_gridlayout = QtWidgets.QGridLayout()
        self.settings_gridlayout.setObjectName("settings_gridlayout")
        self.station_01 = QtWidgets.QPushButton(self.frame_3)
        self.station_01.setObjectName("station_01")
        self.settings_gridlayout.addWidget(self.station_01, 0, 0, 1, 1)
        self.station_02 = QtWidgets.QPushButton(self.frame_3)
        self.station_02.setObjectName("station_02")
        self.settings_gridlayout.addWidget(self.station_02, 0, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.frame_3)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 36))
        self.save_btn.setObjectName("save_btn")
        self.settings_gridlayout.addWidget(self.save_btn, 0, 2, 1, 1)
        self.station_03 = QtWidgets.QPushButton(self.frame_3)
        self.station_03.setObjectName("station_03")
        self.settings_gridlayout.addWidget(self.station_03, 1, 0, 1, 1)
        self.station_04 = QtWidgets.QPushButton(self.frame_3)
        self.station_04.setObjectName("station_04")
        self.settings_gridlayout.addWidget(self.station_04, 1, 1, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.frame_3)
        self.reset_btn.setMinimumSize(QtCore.QSize(0, 36))
        self.reset_btn.setObjectName("reset_btn")
        self.settings_gridlayout.addWidget(self.reset_btn, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.settings_gridlayout)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.settings_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.setting_page)
        self.mapping_page = QtWidgets.QWidget()
        self.mapping_page.setObjectName("mapping_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mapping_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mapping_frame = QtWidgets.QFrame(self.mapping_page)
        self.mapping_frame.setMinimumSize(QtCore.QSize(400, 500))
        self.mapping_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mapping_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mapping_frame.setObjectName("mapping_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mapping_frame)
        self.verticalLayout_9.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.mapping_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.close_mapping = QtWidgets.QPushButton(self.frame_5)
        self.close_mapping.setObjectName("close_mapping")
        self.verticalLayout_7.addWidget(self.close_mapping, 0, QtCore.Qt.AlignRight)
        self.mapping_gif = QtWidgets.QLabel(self.frame_5)
        self.mapping_gif.setMinimumSize(QtCore.QSize(0, 200))
        self.mapping_gif.setText("")
        self.mapping_gif.setObjectName("mapping_gif")
        self.verticalLayout_7.addWidget(self.mapping_gif)
        self.mapping_info = QtWidgets.QLabel(self.frame_5)
        self.mapping_info.setAlignment(QtCore.Qt.AlignCenter)
        self.mapping_info.setObjectName("mapping_info")
        self.verticalLayout_7.addWidget(self.mapping_info)
        self.start_map = QtWidgets.QPushButton(self.frame_5)
        self.start_map.setMinimumSize(QtCore.QSize(36, 36))
        self.start_map.setMaximumSize(QtCore.QSize(36, 36))
        self.start_map.setStyleSheet("image: url(:/images/resources/record.png);\n"
"background-color: #2b2d2e;\n"
"border-radius: 18px;")
        self.start_map.setText("")
        self.start_map.setObjectName("start_map")
        self.verticalLayout_7.addWidget(self.start_map, 0, QtCore.Qt.AlignHCenter)
        self.save_frame = QtWidgets.QFrame(self.frame_5)
        self.save_frame.setMaximumSize(QtCore.QSize(16777215, 0))
        self.save_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.save_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_frame.setObjectName("save_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.save_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.save_frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.save_frame)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: transparent;\n"
"border: 0px;\n"
"font: 12pt \"Wix Madefor Display\";\n"
"color: white;\n"
"    selection-background-color: #2b2d2e;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.save_map = QtWidgets.QPushButton(self.save_frame)
        self.save_map.setMinimumSize(QtCore.QSize(0, 36))
        self.save_map.setObjectName("save_map")
        self.verticalLayout_6.addWidget(self.save_map)
        self.set_initial = QtWidgets.QPushButton(self.save_frame)
        self.set_initial.setMinimumSize(QtCore.QSize(0, 36))
        self.set_initial.setObjectName("set_initial")
        self.verticalLayout_6.addWidget(self.set_initial)
        self.verticalLayout_7.addWidget(self.save_frame)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.verticalLayout_8.addWidget(self.mapping_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.mapping_page)
        self.rviz_page = QtWidgets.QWidget()
        self.rviz_page.setObjectName("rviz_page")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.rviz_page)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_6 = QtWidgets.QFrame(self.rviz_page)
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.rviz_page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.rviz_frame = QtWidgets.QFrame(self.frame_4)
        self.rviz_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rviz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rviz_frame.setObjectName("rviz_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.rviz_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_13.addWidget(self.rviz_frame)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.start_map_2 = QtWidgets.QPushButton(self.frame_8)
        self.start_map_2.setMinimumSize(QtCore.QSize(36, 36))
        self.start_map_2.setMaximumSize(QtCore.QSize(36, 36))
        self.start_map_2.setStyleSheet("image: url(:/images/resources/record.png);\n"
"background-color: #2b2d2e;\n"
"border-radius: 18px;")
        self.start_map_2.setText("")
        self.start_map_2.setObjectName("start_map_2")
        self.verticalLayout_14.addWidget(self.start_map_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.frame_8, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_10.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.rviz_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.central_frame)
        self.bottom_frame = QtWidgets.QFrame(self.centralwidget)
        self.bottom_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.bottom_frame)
        self.label_2.setMinimumSize(QtCore.QSize(28, 28))
        self.label_2.setStyleSheet("image: url(:/images/resources/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.bottom_frame)
        self.label_3.setStyleSheet("QLabel{\n"
"font: 12pt \"Wix Madefor Display\";\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.bottom_frame, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Önder Grup"))
        self.label_10.setText(_translate("MainWindow", "Ready"))
        self.label_11.setText(_translate("MainWindow", "s"))
        self.set_timer.setText(_translate("MainWindow", "Set"))
        self.station_1.setText(_translate("MainWindow", "station#1"))
        self.station_2.setText(_translate("MainWindow", "station#2"))
        self.station_3.setText(_translate("MainWindow", "station#3"))
        self.station_4.setText(_translate("MainWindow", "station#4"))
        self.go_home.setText(_translate("MainWindow", "Home"))
        self.start_planner.setText(_translate("MainWindow", "Start"))
        self.close_settings.setText(_translate("MainWindow", "x"))
        self.settings_info.setText(_translate("MainWindow", "info"))
        self.load_map.setText(_translate("MainWindow", "Load map"))
        self.new_map.setText(_translate("MainWindow", "+New map"))
        self.station_01.setText(_translate("MainWindow", "station#1"))
        self.station_02.setText(_translate("MainWindow", "station#2"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.station_03.setText(_translate("MainWindow", "station#3"))
        self.station_04.setText(_translate("MainWindow", "station#4"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.close_mapping.setText(_translate("MainWindow", "x"))
        self.mapping_info.setText(_translate("MainWindow", "gif status"))
        self.label_5.setText(_translate("MainWindow", "Name:"))
        self.save_map.setText(_translate("MainWindow", "Save"))
        self.set_initial.setText(_translate("MainWindow", "Set initial"))
        self.label_3.setText(_translate("MainWindow", "NCT Robotik"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
